version: '3.8'

services:
  django_cli:
    build: .
    container_name: django_cli_container
    volumes:
      - .:/app
    networks:
      - ollama_network
      - scrapingcourse_scraper_app_network
    environment:
      - DB_NAME=scraping_db
      - DB_USER=munne
      - DB_PASSWORD=munne123
      - DB_HOST=postgres
      - DB_PORT=5432
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    command: sh -c "wait-for-it postgres:5432 -- python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    restart: unless-stopped
    command: serve
    networks:
      - ollama_network
      - scrapingcourse_scraper_app_network

volumes:
  ollama_data:

networks:
  ollama_network:
    driver: bridge
  scrapingcourse_scraper_app_network:
    external: true
